---

- name: set interpreter
  set_fact:
    ansible_python_interpreter: /usr/libexec/platform-python
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version >= '8'
  tags: always

